package rashjz.info;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import org.springframework.beans.factory.annotation.Autowired;
import rashjz.info.jpa.CustomerRepository;


@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class StatsViewDesign extends VerticalLayout {

    @Autowired
    protected final CustomerRepository repository;

    public StatsViewDesign(CustomerRepository repository) {
        this.repository = repository;
        Design.read(this);
    }




}
